### ISSUE TITLE
Bài stack

### ISSUE THREAD

**Issue by ngocdaothanh** [hadv/Hallelujah#5]
https://github.com/hadv/Hallelujah/blob/6e3335f4529b7162c246a92ed9ecd398fb31a6c7/src/com/company/demo/stack/Stack.java
- Đoạn văn đầu tiên trong Javadoc k dùng `<p>`. `<p>` dùng để ngăn cách các đoạn văn.
- Lúc pop trả về null, thì có vấn đề nếu cho push phần tử là null. Đây là vấn đề thường gặp khi thiết kế collection. Có 2 cách giải quyết: cấm push null hoặc throw exception khi pop. Các collection chuẩn của Java đều ghi chú về vấn đề này trong Javadoc.

Bgio đến bước tiếp theo của đề bài:
Hãy thêm vào phương thức `getMax` để lấy ra phần tử lớn nhất.

**Comment by hadv** [comment]
> Đoạn văn đầu tiên trong Javadoc k dùng <p>

OK Ngọc, anh bỏ thẻ `<p>` đi rồi.

> Lúc pop trả về null,

Hôm qua lúc đi ngủ anh cũng nghĩ đến trường hợp này :smile:  Anh đã thay đổi để không cho phép push giá trị null. Nếu push giá trị null sẽ throw ra `UnsupportedOperationException`.

> Hãy thêm vào phương thức getMax để lấy ra phần tử lớn nhất.

Anh đã commit code thêm hàm `getMax()` rồi. Vì sẽ cần phải so sánh nên anh thay đôi bắt buộc T phải implement interface `Comparable<T>`. Giá trị lớn nhất sẽ được kiểm tra và cập nhật khi một phần tử mới được push vào stack.

https://github.com/hadv/Hallelujah/commit/9f28cd54e588247264783d4fc111e7bff602cc58

**Comment by ngocdaothanh** [comment]
Bài anh viết bị bug đấy.
Đây là đề pv cty G, nên mặc dù k khó, nhưng k cẩn thận là toi ngay.

**Comment by hadv** [comment]
Ừ nhỉ, a quên chưa cập nhật lại max khi pop out phần từ ra khỏi stack rồi :disappointed:

**Comment by hadv** [comment]
Anh vừa commit source code bổ sung cho việc tính toán lại giá trị max sau mỗi lần gọi hàm `pop` rồi Ngọc nhé

https://github.com/hadv/Hallelujah/commit/d0ef60341b71adf2fd1ecb9639f19774decaedd3

**Comment by hadv** [comment]
Anh code lại phương thức `getMax()`. Sẽ không cập nhật giá trị lớn nhất sau mỗi lần push/pop nữa mà sẽ tính toán giá trị max chỉ khi call phương thức `getMax()`

**Comment by ngocdaothanh** [comment]
Câu hỏi liên hoàn cước tiếp theo:
Độ phức tạp tính toán của `getMax` anh vừa viết bằng bao nhiêu?
https://github.com/hadv/Hallelujah/blob/f71095fbf6b69930a8fd0b5494836c99f6cd670c/src/com/company/demo/stack/Stack.java

**Comment by hadv** [comment]
> Độ phức tạp tính toán của getMax anh vừa viết bằng bao nhiêu?

Theo anh thì độ phức tạp tính toán của `getMax` là `O(n)`; trong đó `n` là số lượng phần tử đang có trong stack.

**Comment by ngocdaothanh** [comment]
Tiếp theo: Hãy sửa để nó thành O(1).

**Comment by hadv** [comment]
> Tiếp theo: Hãy sửa để nó thành O(1).

A có tham khảo cách làm thì có thể biến getMax() thành O(1) như sau

https://github.com/hadv/Hallelujah/commit/aeb1d530020616d6a5589a6c0610c7be5e2af028

Tuy nhiên, a vừa nghĩ ra để tối ưu bộ nhớ thì thay vì lưu toàn bộ giá trị max thì chỉ cần lưu index của max trong array data là được.

**Comment by hadv** [comment]
> Tuy nhiên, a vừa nghĩ ra để tối ưu bộ nhớ thì thay vì lưu toàn bộ giá trị max thì chỉ cần lưu index của max trong array data là được.

A có code lại theo hướng chỉ lưu index của giá trị max để tối ưu bộ nhớ như sau. Ngọc xem giúp anh nhé!

https://github.com/hadv/Hallelujah/commit/0846f0cb4a1960ca6ea9953d5d204d5f928f2e78

**Comment by ngocdaothanh** [comment]
Ngon rồi.

Anh làm bài mới nhé:
Công ty game nọ có cái game rất hot, hàng ngày DAU khoảng 10 triệu.
Hãy viết chương trình để hàng ngày tính ranking top 100 user có điểm chơi game cao nhất.
