### ISSUE TITLE
abc

### ISSUE THREAD

**Issue by ngocdaothanh** [hadv/Hallelujah#8]
Bài 1:
Hãy viết hàm tính toán ra các kết hợp của một chuỗi. Ví dụ cho abc, thì sẽ tính ra:
a
b
c
ab
ac
abc
acb
...

```
List<String> f1(String s)
```

Bài 2:
Tương tự bài 1, chỉ khác là ví dụ cho abc, thì sẽ tính ra:
abc
acb
bac
bca
...

**Comment by hadv** [comment]
> Bài 2:

Bài số 2 thì a nghĩ là tìm tất cả các hoán vị có n phần tử. A thấy dễ làm hơn nên anh làm bài số 2 trước.
Ngọc xem giúp anh nhé.

https://github.com/hadv/Hallelujah/commit/b74bcce7030c6d6af28f274130009c2a0141d9df

Bài số 1 thì ngày mai anh sẽ tiếp tục làm.

**Comment by ngocdaothanh** [comment]
Anh viết ra ý tưởng về cách làm đi.
Khi phỏng vấn mà xông vào code ào ào ngay thì không được đánh giá cao.
Discuss xong xuôi rồi hẵng code.

**Comment by hadv** [comment]
Hi Ngọc,

Hôm nay anh có đọc thêm chút về lý thuyết hoán vị, chỉnh hợp và tổ hợp.

Để dễ dàng thì bài toán abc là bài toán liệt kê hoán vị tổ hợp của k phần từ từ n phần từ khác nhau, `1 <= k <= n` của một chuỗi (nghĩa là chuỗi đầu vào không chứa các ký tự trùng lặp nhau, ví dụ như chuỗi `"aac"`, `"abb"` là không hợp lệ).

Theo lý thuyết thì bài toán liệt kê hoán vị này có thể sử dụng đệ quy quay lui để thực hiện. 
1. Bài toán thứ nhất thì sẽ liệt kê toàn bộ các hoán vị tổ hợp k phần tử trong n phần tử, k = 1..n
2. Còn bài toán thứ hai thì chỉ là trường hợp đặc biệt của bài toán 1 khi k = n.

Cách anh tiếp cận bài toán sẽ là như vậy. Ngọc xem góp ý giúp anh nhé!

**Comment by ngocdaothanh** [comment]
OK bgio anh code theo tinh thần trên đi.

**Comment by hadv** [comment]
Hi Ngọc,

A code xong Bài 1 và Bài 2 rồi nhé, Ngọc xem giúp anh

https://github.com/hadv/Hallelujah/blob/master/src/com/company/demo/combination/Permutation.java

> Bài 1:

Bài 1 thì a code trong method sau đây

```
public static List<String> f1(String s)
```

> Bài 2:

Như anh đã discuss hôm trước thì Bài 2 là trường hợp đặc biệt của Bài 1 khi k = n; tuy nhiên, anh cũng code riêng trong method sau:

```
public static List<String> f2(String s)
```

**Comment by ngocdaothanh** [comment]
https://github.com/hadv/Hallelujah/blob/284bfc01ba6cd50aa8509fb2b0e1b9fcbbc3c77b/src/com/company/demo/combination/Permutation.java

```
StringPermutation sp = new StringPermutation(len, s);
sp.combination(0);
```

Cái method `combination` trên có lẽ nên để là private.

Câu hỏi: Độ phức tạp tính toán bằng bao nhiêu?

**Comment by hadv** [comment]
> Cái method combination trên có lẽ nên để là private.

uh, công nhận là `sp.combination(0);` cũng vô duyên thật, A chuyển thành private method rồi Ngọc nhé!

https://github.com/hadv/Hallelujah/commit/5c86113dc2be102fb469d30def396aa517c3ce74

> Câu hỏi: Độ phức tạp tính toán bằng bao nhiêu?

A nghĩa độ phức tạp chủ yếu là ở method `combination()`, theo anh thì độ phức tạp của tính toán này là O(k<sup>n</sup>)

**Comment by ngocdaothanh** [comment]
Discussion:
- Về độ phức tạp, thì [bài này](https://en.wikipedia.org/wiki/Permutation) có công thức toán học luôn rồi: `n! / (n - k)!`. Cái giai thừa cho thấy bài này khá là đơn giản, nhưng chỉ cần `n` lớn một chút thì chạy sẽ rất lâu và nhanh bị out of memory nếu lưu lại tất cả kết quả.
- Nếu cần lưu lại kết quả, mà khi nào muốn lấy kết quả tiếp theo thì sẽ gọi hàm `next` (theo tinh thần lazy như cách code đầu của anh), thì anh sẽ làm thế nào?
- Nếu áp dụng tinh thần dynamic programming vào bài này, thì anh sẽ làm thế nào?

**Comment by hadv** [comment]
> Về độ phức tạp, thì bài này có công thức toán học luôn rồi: n! / (n - k)!.

Ừ đúng vậy nhỉ, Anh xem kỹ lại thuật toán thì đúng là như vậy. Vì các step cuối đã bị loại trừ những item đã sử dụng nên độ phức tạp giảm đi một chút

> Nếu cần lưu lại kết quả, mà khi nào muốn lấy kết quả tiếp theo thì sẽ gọi hàm next (theo tinh thần lazy > như cách code đầu của anh), thì anh sẽ làm thế nào?

Theo suy nghĩ của anh để viết theo tinh thần lazy thì kiểu hàm next() thì bước làm sẽ như sau
1. Tính toàn bộ k-combination của chuỗi input n phần từ (k = 1..n)
2. Lần lượt output ra các k-permuatation của từng k-combination cho đến hết.

Ví dụ chuỗi đầu vào là 12345 và cần output ra các chuỗi có 3 phần tử thì sẽ như sau
1. Tính toàn bộ k-combination của chuỗi input 
   123
   124
   125
   134
   135
   234
   235
   345
2. Đối với mỗi k-combination ở trên thì lần lượt in ra các k-permuatation
   123
   132
   213
   231
   312
   312
   124
   142
   214
   ...
   ...

> Nếu áp dụng tinh thần dynamic programming vào bài này, thì anh sẽ làm thế nào?

Phần này thì để anh suy nghĩ thêm vì a cũng chưa thạo lập trình DP lắm :)

**Comment by ngocdaothanh** [comment]
Cái discussion thứ 2 câu hỏi của em k rõ ràng, đọc lại em cũng k nhớ ý đồ là gì, nên bỏ qua vậy.

Về discussion thứ 3, anh hãy code thành file mới, theo giải thuật có ý tưởng sau:

Giả sử input là `Set('1', '2', '3', '4', '5')`, hàm tính toán là `Set<String> f(Set<Char> input)` thì sẽ tính:
`"1" + từng cái trong kết quả của f(input không chứa '1')`

`"2" + từng cái trong kết quả của f(input không chứa '2')`

`"3" + từng cái trong kết quả của f(input không chứa '3')`

`"4" + từng cái trong kết quả của f(input không chứa '4')`

`"5" + từng cái trong kết quả của f(input không chứa '5')`

Nghĩa là lấy từng phần tử rồi ghép với phần tính toán bài toán con không chứa phần tử ấy.

Cái f(input không chứa 'x'`) lại đệ qui tiếp đến khi nào số lượng phần tử là 1.

Tóm lại ý tưởng DP là:
- Đệ qui, với hình dạng bài toán con nó trông giống hình dạng bài toán to (đồng dạng). (Nếu cũng gọi đệ qui, nhưng k đồng dạng thì k đúng tinh thần DP.)
- Nếu có thể thì cache lại kết quả bài toán con để tái sử dụng.

**Comment by hadv** [comment]
Hi Ngọc,

A đã implement code theo discussion thứ 3 như sau nhé

https://github.com/hadv/Hallelujah/blob/master/src/com/company/demo/combination/Permut.java

Theo anh thì lời giải của bài toán này không có sự lặp lại ở bài toán con nên không cần sử dụng cache kết quả.

**Comment by ngocdaothanh** [comment]
https://github.com/hadv/Hallelujah/blob/a1628de8fc95d4ec7c38a542d3ee7efed56661f4/src/com/company/demo/combination/Permut.java

Trông ngắn gọn quá nhỉ!

Các tài liệu hdan phỏng vấn đều nói là hầu hết các bài đều có hướng giải là dùng DP, theo tinh thần là chia bài toán to thành các bài toán nhỏ _đồng dạng_.

Nếu viết thành class, thì cái class anh viết thiết kế k thích lắm:
- Style: output nên đặt là private.
- API: Gọi hàm permut xong phải gọi thêm getOutput mới lấy được kết quả.

Thường bài phỏng vấn đều ngắn, nên đôi lúc như bài này có thể viết thành 1 hàm (nếu được), k cần phắn thành nguyên cái class làm gì cho nó loằng ngoằng.
